### ISSUE TITLE
Automate Deploys using Travis

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#39]

**Comment by awesomescot** [comment]
As it turns out travis won't allow deploys to random servers.  It is possible to use github to make a post request to our site, which could do a deploy.  But I think this is too much work for the advantages.  So I'm just going to write a deploy script that we can manually run when we want to deploy.

**Comment by awesomescot** [comment]
I've created a script in /home/scot/deploy.sh, that I will test a few more times and then add to the repo.
